### ISSUE TITLE
Соединение с instance не удаётся

### ISSUE THREAD

**Issue by sergey-shambir** [ivan-uskov/key-value#1]
В ветке js_sdk реализована обёртка для запуска Instance и запроса/получения ключей
К сожалению, соединиться с instance не удаётся

В консоли браузера валится  запрос run:
```js
hubClient.list()
hubClient.run('').then((client) => { window.client = client; })
```

При этом instance запускается, но соединиться с ним не удаётся

**Comment by sergey-shambir** [comment]
Буду искать причины дальше, возможно, стоит посмотреть вдвоём.

**Comment by sergey-shambir** [comment]
Буду искать причины дальше, возможно, стоит посмотреть вдвоём.

**Comment by ivan-uskov** [comment]
Это происходило из-за неправильных параметров подключения
